### ISSUE TITLE
openGL加载名为wepenguin的模型时报错

### ISSUE THREAD

**Issue by xujingguo58** [91Shenlan/WeAr#1]
别的模型可以正常加载，但是使用该模型后提示如下log
10-09 20:36:36.538 19421-19447/? E/AndroidRuntime: FATAL EXCEPTION: GLThread 858
    Process: com.google.ar.core.examples.java.helloar, PID: 19421
    java.lang.IllegalArgumentException: invalid Bitmap format
        at android.opengl.GLUtils.texImage2D(GLUtils.java:155)
        at com.webank.mbank.ar.rendering.ObjectRenderer.createOnGlThread(ObjectRenderer.java:129)
        at com.webank.mbank.ar.HelloArActivity.onSurfaceCreated(HelloArActivity.java:334)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1575)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1293)

**Comment by 91Shenlan** [comment]
不好意思，现在才回复你。这个问题是因为模型太复杂了，很多手机加载不出来导致的，我这边也出现过。你可以将我的模型换成ARCore的机器人，再调整一下绘制时的缩放比例即可。
